import Head from "next/head";

import JobsSection from "../components/JobsSection";

import { Job, getJobs } from "../lib/getJobs";
import { organizeJobsByDate } from "../lib/organizeJobsByDate";

import { useState } from "react";
import Link from "next/link";

export default function Home({ jobs }: { jobs: Job[] }) {
  const [numberOfDisplayJobs, setNumberOfDisplayJobs] = useState(10);

  const displayJobs = jobs?.slice(0, numberOfDisplayJobs);
  const jobsByDate = organizeJobsByDate(displayJobs);

  const jobsSections = [];

  for (const date in jobsByDate) {
    jobsSections.push(
      <JobsSection key={date} time={date} jobs={jobsByDate[date]} />
    );
  }

  const handleOnClickShowMoreJobs = () => {
    if (numberOfDisplayJobs < jobs.length) {
      if (numberOfDisplayJobs + 10 < jobs.length) {
        setNumberOfDisplayJobs(numberOfDisplayJobs + 10);
      } else {
        setNumberOfDisplayJobs(
          numberOfDisplayJobs + (jobs.length - numberOfDisplayJobs)
        );
      }
    }
  };

  return (
    <>
      <Head>
        <title>Next Hacker Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:max-w-screen-lg container mx-auto px-8 grow">
        <h1 className="text-4xl font-bold mb-8">
          <span className="inline-block underline bg-black font-heading text-white px-14 py-6 ">
            Next Hacker Jobs
          </span>
        </h1>
        <ul className="">
          {jobsSections}
        </ul>
        <div className="py-8 my-8">
          <div className="text-center uppercase font-bold my-4">
            <span>
              Showing {numberOfDisplayJobs} of {jobs.length} jobs
            </span>
          </div>
          <div className="text-center my-4">
            {numberOfDisplayJobs < jobs.length ? (
              <button
                onClick={handleOnClickShowMoreJobs}
                className="text-lg border-2 border-black shadow-md bg-pink font-heading uppercase cursor-pointer px-8 py-4"
              >
                Show More Jobs
              </button>
            ) : (
              <button
                onClick={handleOnClickShowMoreJobs}
                className="text-lg border-2 border-black shadow-md bg-white font-heading uppercase cursor-not-allowed px-8 py-4"
              >
                No More Jobs to Show
              </button>
            )}
          </div>
        </div>
      </main>
      <footer className="mt-4 mb-4">
        <div className="text-center">
          Copyright © 2023 Next Hacker News. All rights reserved.
        </div>
        <div className="text-center">
          <Link
            href="https://github.com/writeonlycode/next-hacker-news"
            className="underline"
          >
            Next.JS Project by Iago Bozza.
          </Link>
        </div>
        <div className="text-center">
          <Link
            href="https://www.figma.com/community/file/1107425834181017461"
            className="underline"
          >
            Inspired in a Desing by Sofia Dinatolo.
          </Link>
        </div>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  return { props: { jobs: await getJobs() } };
}
